"""
This file reads the generated encoding.h file and extracts specific symbol arrays, 
to create a combined matrix representation for displaying the plate form of "15:12" in polar coordinates.

It can then be displayed using the script image_display_test.py
"""
import re

# Encoding file generated by the previous script
ENC_FILE = "image_conversion/converted_images/encoding_120.h"

# Symbols to extract to form "15h12"
SYMBOLS = ["c1n1", "c2n5", "c3n1", "c4n2"]

# Function to extract array data from the C file
def extract_array(content, name):
    pattern = rf"const uint16_t {name}\[.*?\] PROGMEM = \{{(.*?)\}};"
    m = re.search(pattern, content, re.S)
    if not m:
        raise ValueError(f"Array {name} not found")
    block = m.group(1)
    lines = [x.strip().rstrip(",") for x in block.splitlines() if "0b" in x]
    values = [int(x, 2) for x in lines]
    return values

# Convert integer values to binary string rows
def to_binary_rows(values):
    rows = []
    for v in values:
        b = format(v, "016b")  # 16 bits
        rows.append([c for c in b])
    return rows

with open(ENC_FILE, "r") as f:
    content = f.read()

# Build the full matrix for "15h12"
full_matrix = []
for sym in SYMBOLS:
    arr = extract_array(content, sym)
    rows = to_binary_rows(arr)
    full_matrix.extend(rows)

# Write the combined matrix to 1512.txt
with open("1512.txt", "w") as f:
    for row in full_matrix:
        f.write("{" + ",".join(f'"{x}"' for x in row) + "},\n")

print("File 1512.txt generated.")
